# Generated by Django 5.2.4 on 2025-08-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_technology_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='discription',
            field=models.TextField(blank=True, default='No discription curerntly', null=True),
        ),
    ]
